# Generated by Django 4.0.4 on 2022-08-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_remove_orderitem_price_reciept_customer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Whatsapp_Number',
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_Number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
