# Generated by Django 4.0.4 on 2022-08-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_remove_customer_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sumTotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
