# Generated by Django 4.0.4 on 2022-08-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_rename_phone_number_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sumTotal',
        ),
    ]
