# Generated by Django 4.0.4 on 2022-08-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0007_remove_customer_address_reciept_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.customer'),
        ),
    ]
