# Generated by Django 4.0.4 on 2022-08-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0009_rename_address_reciept_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='contact',
            new_name='phone_contact',
        ),
    ]
