# Generated by Django 4.0.4 on 2022-08-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0010_rename_contact_reciept_phone_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
