# Generated by Django 4.0.4 on 2022-08-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0011_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='order',
        ),
    ]
