# Generated by Django 4.0.4 on 2022-08-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0012_remove_reciept_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='order',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
