# Generated by Django 4.0.4 on 2022-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0013_reciept_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='about',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='order',
            field=models.CharField(max_length=1000),
        ),
    ]
