# Generated by Django 4.0.4 on 2022-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0014_customer_about_alter_reciept_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='order',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
